server:
  port: 8058
  
  # Spring properties
spring:  
  application:
    name: profesores

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
